# Generated by Django 2.0.7 on 2018-08-03 15:17

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation_log',
            fields=[
                ('Donation_log_id', models.AutoField(primary_key=True, serialize=False, verbose_name='流水id')),
                ('donate_money', models.FloatField(verbose_name='捐助金额')),
                ('donate_at', models.DateTimeField(auto_now_add=True, verbose_name='捐助时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '捐助流水',
            },
        ),
        migrations.CreateModel(
            name='prj_development',
            fields=[
                ('prj_development_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40, verbose_name='进程题目')),
                ('introduce', models.TextField(verbose_name='进程简介')),
                ('image', models.ImageField(max_length=1024, upload_to='img', verbose_name='图片')),
                ('year', models.CharField(max_length=10, verbose_name='进程发生年份')),
                ('date', models.CharField(max_length=30, verbose_name='进程发生月日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '众筹项目进程',
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('proj_class', models.CharField(max_length=50, verbose_name='项目类别')),
                ('project_id', models.AutoField(primary_key=True, serialize=False, verbose_name='项目id')),
                ('name', models.CharField(max_length=30, verbose_name='项目名称')),
                ('introduce', DjangoUeditor.models.UEditorField(verbose_name='项目简介')),
                ('action', models.TextField(verbose_name='具体行动')),
                ('befor_image', models.ImageField(upload_to='img', verbose_name='首页项目图片')),
                ('later_image', models.ImageField(upload_to='img', verbose_name='进入后项目图片')),
                ('target_money', models.FloatField(verbose_name='目标金额')),
                ('now_money', models.FloatField(verbose_name='已筹金额')),
                ('people_num', models.IntegerField(verbose_name='帮助人数')),
                ('see_num', models.IntegerField(verbose_name='浏览人数')),
                ('time_begin', models.DateField(verbose_name='开始时间')),
                ('time_out', models.DateField(verbose_name='结束时间')),
                ('state', models.IntegerField(choices=[(0, '审核中'), (1, '通过'), (2, '未通过')], verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('is_display', models.IntegerField(choices=[(0, '展示在首页'), (1, '不展示')], default=1, verbose_name='是否展示')),
                ('is_delete', models.IntegerField(choices=[(0, '已删除'), (1, '未删除')], default=1)),
            ],
            options={
                'verbose_name': '众筹项目',
            },
        ),
    ]
