# Generated by Django 2.0.3 on 2018-07-28 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prj_development',
            old_name='name',
            new_name='name_id',
        ),
    ]
