# Generated by Django 2.0.7 on 2018-08-03 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发起人用户名'),
        ),
        migrations.AddField(
            model_name='prj_development',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donate.project', verbose_name='项目名称'),
        ),
        migrations.AddField(
            model_name='donation_log',
            name='Donation_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='捐助人姓名'),
        ),
        migrations.AddField(
            model_name='donation_log',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='donate.project', verbose_name='捐助项目名称'),
        ),
    ]
