# Generated by Django 2.0.3 on 2018-08-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_auto_20180803_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prj_development',
            name='image',
            field=models.ImageField(max_length=1024, upload_to='', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='project',
            name='befor_image',
            field=models.ImageField(max_length=1024, upload_to='', verbose_name='首页项目图片'),
        ),
        migrations.AlterField(
            model_name='project',
            name='later_image',
            field=models.ImageField(max_length=1024, upload_to='', verbose_name='进入后项目图片'),
        ),
    ]
