# Generated by Django 2.0.3 on 2018-07-28 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0003_auto_20180728_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prj_development',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donate.project', verbose_name='项目名称'),
        ),
    ]
