# Generated by Django 2.0.3 on 2018-07-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0004_auto_20180728_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.IntegerField(choices=[(0, '审核中'), (1, '通过'), (2, '未通过')], verbose_name='状态'),
        ),
    ]
