# Generated by Django 2.0.3 on 2018-07-28 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0005_auto_20180728_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prj_development',
            options={'verbose_name': '众筹项目进程'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '众筹项目'},
        ),
    ]
