# Generated by Django 2.0.3 on 2018-07-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0006_auto_20180728_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proj_class',
            field=models.IntegerField(choices=[(0, '教育助学'), (1, '扶贫助困')], verbose_name='项目类别'),
        ),
    ]
