# Generated by Django 2.0.3 on 2018-07-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0007_auto_20180728_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prj_development',
            name='prj_development_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='项目id'),
        ),
        migrations.AddField(
            model_name='prj_development',
            name='date',
            field=models.CharField(default=None, max_length=30, verbose_name='进程发生月日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prj_development',
            name='year',
            field=models.CharField(default=None, max_length=10, verbose_name='进程发生年份'),
            preserve_default=False,
        ),
    ]
