# Generated by Django 2.0.3 on 2018-07-30 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donate', '0008_auto_20180728_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation_log',
            fields=[
                ('Donation_log_id', models.AutoField(primary_key=True, serialize=False, verbose_name='流水id')),
                ('donate_money', models.IntegerField(verbose_name='捐助金额')),
                ('donate_at', models.DateTimeField(auto_now_add=True, verbose_name='捐助时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('Donation_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='捐助人姓名')),
            ],
            options={
                'verbose_name': '捐助流水',
            },
        ),
        migrations.AddField(
            model_name='donation_log',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='donate.project', verbose_name='捐助项目名称'),
        ),
    ]
