# Generated by Django 2.0.3 on 2018-07-30 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donate', '0009_auto_20180730_1913'),
    ]

    operations = [

        migrations.AlterField(
            model_name='donation_log',
            name='donate_money',
            field=models.FloatField(verbose_name='捐助金额'),
        ),
        migrations.AlterField(
            model_name='project',
            name='now_money',
            field=models.FloatField(verbose_name='已筹金额'),
        ),

        migrations.AlterField(
            model_name='project',
            name='target_money',
            field=models.FloatField(verbose_name='目标金额'),
        ),
    ]
