# Generated by Django 2.0.3 on 2018-07-31 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donate', '0010_auto_20180730_2135'),
    ]

    operations = [

        migrations.AlterField(
            model_name='project',
            name='time_begin',
            field=models.DateField(verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='time_out',
            field=models.DateField(verbose_name='结束时间'),
        ),
    ]
