# Generated by Django 2.0.3 on 2018-07-31 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donate', '0011_auto_20180731_0828'),
    ]

    operations = [



        migrations.AlterField(
            model_name='project',
            name='proj_class',
            field=models.CharField(max_length=50, verbose_name='项目类别'),
        ),

    ]
