# Generated by Django 2.0.3 on 2018-07-31 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donate', '0013_auto_20180731_1139'),
    ]

    operations = [

        migrations.AddField(
            model_name='project',
            name='is_delete',
            field=models.IntegerField(choices=[(0, '已删除'), (1, '未删除')], default=1),
        ),


    ]
