# Generated by Django 2.0.3 on 2018-08-02 09:26

import DjangoUeditor.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donate', '0014_auto_20180731_1445'),
    ]

    operations = [


        migrations.AlterField(
            model_name='project',
            name='introduce',
            field=DjangoUeditor.models.UEditorField(verbose_name='项目简介'),
        ),

    ]
