# Generated by Django 2.0.7 on 2018-08-03 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donate', '0015_auto_20180802_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prj_development',
            name='time',
        ),
        migrations.AddField(
            model_name='project',
            name='user_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发起人用户名'),
        ),
        migrations.AlterField(
            model_name='prj_development',
            name='prj_development_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='项目id'),
        ),
    ]
