# Generated by Django 2.0.7 on 2018-08-03 15:17

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_publish', models.CharField(choices=[('publish', '发布'), ('manuscript', '草稿')], default='manuscript', max_length=10, verbose_name='新闻状态')),
                ('title', models.CharField(max_length=128, verbose_name='新闻标题')),
                ('image', models.ImageField(upload_to='title_images', verbose_name='新闻标题图片')),
                ('source_from', models.CharField(max_length=32, verbose_name='新闻来源')),
                ('general_situation', models.TextField(verbose_name='新闻概况')),
                ('text', DjangoUeditor.models.UEditorField(verbose_name='新闻内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
            },
        ),
        migrations.CreateModel(
            name='Nosatis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News')),
            ],
            options={
                'verbose_name': '被赞：不喜欢',
                'verbose_name_plural': '被赞：不喜欢',
            },
        ),
        migrations.CreateModel(
            name='Notverysatid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News')),
            ],
            options={
                'verbose_name': '被赞：一般',
                'verbose_name_plural': '被赞：一般',
            },
        ),
        migrations.CreateModel(
            name='Satis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News')),
            ],
            options={
                'verbose_name': '被赞：喜欢',
                'verbose_name_plural': '被赞：喜欢',
            },
        ),
    ]
