# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-30 18:42
from __future__ import unicode_literals

import datetime
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户id')),
                ('user_realname', models.CharField(max_length=12, verbose_name='真实姓名')),
                ('user_nickname', models.CharField(max_length=10, null=True, verbose_name='昵称')),
                ('user_email', models.CharField(max_length=30, verbose_name='邮箱')),
                ('user_id_card_number', models.CharField(max_length=19, verbose_name='身份证号')),
                ('user_mobile', models.CharField(max_length=11, verbose_name='联系电话')),
                ('user_qq', models.CharField(max_length=12, verbose_name='联系QQ')),
                ('user_home_address', models.CharField(max_length=100, verbose_name='家庭住址')),
                ('user_company_name', models.CharField(max_length=100, verbose_name='单位名称')),
                ('user_gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=10)),
                ('user_hand_portrait', models.ImageField(default='image/default.png', null=True, upload_to='image/%Y/%m', verbose_name='头像')),
                ('user_signature', models.CharField(default='', max_length=80, null=True, verbose_name='个性签名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='VerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('email_or_mobile', models.CharField(default=0, max_length=50, verbose_name='邮箱或手机')),
                ('send_type', models.CharField(choices=[('mobileregister', '手机注册'), ('emailregister', '邮箱注册'), ('mobileforget', '手机找回密码'), ('emailforget', '邮箱找回密码')], max_length=20, verbose_name='验证码类型')),
                ('send_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '验证码',
                'verbose_name_plural': '验证码',
            },
        ),
    ]
