# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-30 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='user_id',
            new_name='id',
        ),
    ]
