# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-31 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_auto_20180730_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='user_nickname',
        ),
    ]
